In [ ]:
import numpy as np
arr = np.arange(21,26)
print(arr[3])
print(arr[-5]) # normal indexing 

In [ ]:
import numpy as np
# how to index 2d array elements 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

arr = np.arange(21,30).reshape((3,3))
print(arr[1,2])

In [ ]:
# fancy indexing
arr = np.array([3,78,23,14,5,6,8,79,100])
index = np.array([[1,2],[3,4]])
print(arr[index])

In [ ]:
# slicing 
arr = np.arange(0,20)
slice_object = slice(1,10,2)
print(arr[slice_object])

In [ ]:
for x in arr:
    print(x)


In [ ]:
# using nditer 
# To modify the elements of an array in-place, you need to set the op_flags parameter to ['readwrite']:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("The original array \n",arr)
for element in np.nditer(arr, op_flags=['readwrite']):
    element[...] = element * 2
    print(element)
print("the modified array \n",arr)


In [ ]:

# You can control the order of iteration using the order parameter. For example, you can iterate in 'C' (row-major) or 'F' (column-major) order:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("C order:")
for element in np.nditer(arr, order='C'): # c language 
    print(element, end=' ')
    
print("\nF order:")
for element in np.nditer(arr, order='F'): # fortan language
    print(element, end=' ')

In [ ]:
# You can iterate over arrays with broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print(a.shape)
print(b.shape)
for x, y in np.nditer([a, b]):
    print(x, y)

In [ ]:
# multi index 
arr = np.array([[1, 2, 3], [4, 5, 6]])

it = np.nditer(arr, flags=['multi_index'])
while not it.finished:
    print(f"Index: {it.multi_index}, Value: {it[0]}")
    it.iternext()

In [35]:
#joining arrays
a = np.array([[1,2],[3,4]])
print (a)
b = np.array([5,6])
print(b)
c = np.concatenate((a,b), axis = None)
print(c)

[[1 2]
 [3 4]]
[5 6]
[1 2 3 4 5 6]


In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[3],[4]])
print(a); print(b)
print(b.shape)
np.concatenate((a,b), axis = 1) # number of rows = same.

[[1 2]
 [3 4]]
[[3]
 [4]]
(2, 1)


array([[1, 2, 3],
       [3, 4, 4]])

In [30]:
a = np.array([[1,2],[3,4]])
print (a)
b = np.array([5,6])
np.concatenate((a,b.T), axis = 1)

[[1 2]
 [3 4]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [31]:
b = np.array([5,6]) # row vector
print(b); print (b.shape)
print (np.transpose(b))


[5 6]
(2,)
[5 6]


In [33]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6]).reshape(1, -1)
print(b)
print(b.shape)
print(b.T)
result = np.concatenate((a, b.T), axis=1)  # for axis = 0, number of columns should be equal.
print(result)


[[5 6]]
(1, 2)
[[5]
 [6]]
[[1 2 5]
 [3 4 6]]


In [34]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6]).reshape(-1, 1)
print (b)
result = np.concatenate((a, b), axis=1)  # number of rows should be equal 
print(result)

[[5]
 [6]]
[[1 2 5]
 [3 4 6]]


In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.stack((a,b))

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
np.column_stack((a,b,c))

In [ ]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.hstack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)
[b,c] = np.hsplit(a,2)  # divide the col by 2
print(b); print(c)

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)
[b,c] = np.vsplit(a,2)  # divide the row by 2
print(b); print(c)

In [37]:
import numpy as np
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Save the array to a .npy file
np.save('array.npy', array)

# Load the array from the .npy file
loaded_array = np.load('array.npy')
print(loaded_array)
# Output: [1 2 3 4 5]

[1 2 3 4 5]


In [38]:
import numpy as np
# Create multiple NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Save the arrays to a .npz file
np.savez('arrays.npz', array1=array1, array2=array2)

# Load the arrays from the .npz file
loaded_arrays = np.load('arrays.npz')
print(loaded_arrays['array1'])  # Output: [1 2 3]
print(loaded_arrays['array2'])  # Output: [4 5 6]

[1 2 3]
[4 5 6]
