Certainly! Here are three questions on the topic of NumPy, focusing on indexing, slicing, fancy indexing, iterator, changing array shape (reshape, ravel), transpose, and np.expand_dims. These questions range from basic to intermediate to industry use case levels, relevant to industry use cases and commonly asked during technical and coding rounds of interviews.

### Basic Level

1. **Indexing and Slicing:**
   - Create a 2D NumPy array with shape (3, 4) containing integers from 1 to 12. Use indexing and slicing to extract:
     - The entire first row.
     - The last two columns.
     - The element at the second row, third column.

### Intermediate Level

2. **Reshape, Ravel, and Transpose:**
   - Given a 1D NumPy array with values from 1 to 16, perform the following operations:
     - Reshape it into a 4x4 array.
     - Flatten the 4x4 array back to a 1D array.
     - Transpose the 4x4 array and print the result.

### Industry Use Case

3. **Fancy Indexing and np.expand_dims:**
   - Assume you have a NumPy array representing the sales data of different products for 6 months:
     ```python
     sales_data = np.array([
         [200, 210, 220, 230, 240, 250],
         [150, 160, 170, 180, 190, 200],
         [300, 310, 320, 330, 340, 350],
         [100, 110, 120, 130, 140, 150]
     ])
     ```
     Write a Python function to:
     - Use fancy indexing to extract the sales data for the second and fourth products.
     - Expand the dimensions of the extracted sales data to include a new axis for potential future operations.
     - Calculate the mean sales for each product across the 6 months and print the results.

### Solutions

#### Basic Level Solution

```python
import numpy as np

# Create a 2D array
arr = np.arange(1, 13).reshape(3, 4)

# Entire first row
first_row = arr[0, :]
print("First row:", first_row)

# Last two columns
last_two_columns = arr[:, -2:]
print("Last two columns:", last_two_columns)

# Element at second row, third column
element = arr[1, 2]
print("Element at second row, third column:", element)
```

#### Intermediate Level Solution

```python
import numpy as np

# Given 1D array
arr = np.arange(1, 17)

# Reshape to 4x4
reshaped_arr = arr.reshape(4, 4)
print("Reshaped to 4x4:\n", reshaped_arr)

# Flatten the array
flattened_arr = reshaped_arr.ravel()
print("Flattened array:", flattened_arr)

# Transpose the 4x4 array
transposed_arr = reshaped_arr.T
print("Transposed array:\n", transposed_arr)
```

#### Industry Use Case Solution

```python
import numpy as np

# Given sales data
sales_data = np.array([
    [200, 210, 220, 230, 240, 250],
    [150, 160, 170, 180, 190, 200],
    [300, 310, 320, 330, 340, 350],
    [100, 110, 120, 130, 140, 150]
])

def analyze_sales(data):
    # Fancy indexing to extract sales data for second and fourth products
    extracted_data = data[[1, 3], :]
    print("Extracted sales data:\n", extracted_data)
    
    # Expand dimensions
    expanded_data = np.expand_dims(extracted_data, axis=1)
    print("Expanded dimensions:\n", expanded_data)
    
    # Calculate mean sales for each product across 6 months
    mean_sales = np.mean(data, axis=1)
    print("Mean sales for each product:", mean_sales)

analyze_sales(sales_data)
```

### Explanation

1. **Basic Level:**
   - This question demonstrates how to perform basic indexing and slicing on a NumPy array, which is a fundamental skill in data manipulation and analysis.

2. **Intermediate Level:**
   - This question covers reshaping an array, flattening it back to 1D, and transposing it. These operations are essential for handling data in different shapes and formats, which is a common task in data analysis.

3. **Industry Use Case:**
   - This question involves fancy indexing to select specific rows, expanding dimensions for potential future operations, and calculating aggregate statistics (mean sales). This simulates a real-world scenario where you might need to preprocess and analyze data from a multidimensional array.

These questions and solutions cover key NumPy functionalities relevant to data analysis and manipulation, helping to solidify your understanding of these concepts.

In [42]:
# Basic Level

# 1. **Indexing and Slicing:**
#    - Create a 2D NumPy array with shape (3, 4) containing integers from 1 to 12. Use indexing and slicing to extract:
#      - The entire first row.
#      - The last two columns.
#      - The element at the second row, third column.

import numpy as np

arr = np.arange(1,13).reshape(3,4)

print(arr,"\n")

print(arr[:1])
print("\n")
print(arr[:,2:])
print("\n")
print(arr[1:2,2:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 2 3 4]]


[[ 3  4]
 [ 7  8]
 [11 12]]


[[7]]


In [50]:
# 2. **Reshape, Ravel, and Transpose:**
#    - Given a 1D NumPy array with values from 1 to 16, perform the following operations:
#      - Reshape it into a 4x4 array.
#      - Flatten the 4x4 array back to a 1D array.
#      - Transpose the 4x4 array and print the result.

import numpy as np

arr = np.arange(1,17).reshape(4,4)
print(arr)
arr.flatten()

b = np.transpose(arr)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [23]:
# 3. **Fancy Indexing and np.expand_dims:**
#    - Assume you have a NumPy array representing the sales data of different products for 6 months:
#      ```python
#      sales_data = np.array([
#          [200, 210, 220, 230, 240, 250],
#          [150, 160, 170, 180, 190, 200],
#          [300, 310, 320, 330, 340, 350],
#          [100, 110, 120, 130, 140, 150]
#      ])
#      ```
#      Write a Python function to:
#      - Use fancy indexing to extract the sales data for the second and fourth products.
#      - Expand the dimensions of the extracted sales data to include a new axis for potential future operations.
#      - Calculate the mean sales for each product across the 6 months and print the results.
# import numpy as np
# sales_data = np.array([[
#          [200, 210, 220, 230, 240, 250],
#          [150, 160, 170, 180, 190, 200],
#          [300, 310, 320, 330, 340, 350],
#          [100, 110, 120, 130, 140, 150]
# ]]) 

# print(sales_data[[0,0,0,0,0,0],[1,1,1,1,1,1],[0,1,2,3,4,5]])

import numpy as np
sales_data = np.array([
         [200, 210, 220, 230, 240, 250],
         [150, 160, 170, 180, 190, 200],
         [300, 310, 320, 330, 340, 350],
         [100, 110, 120, 130, 140, 150]
]) 

print(sales_data[[1,1,1,1,1,1],[0,1,2,3,4,5]])

print(sales_data[[3,3,3,3,3,3],[0,1,2,3,4,5]])
print("\n")
sales_data_new = np.expand_dims(sales_data, axis = 1)
print(sales_data_new)
print("\n")

aver= np.mean(sales_data, axis=0)

print(aver)

[150 160 170 180 190 200]
[100 110 120 130 140 150]


[[[200 210 220 230 240 250]]

 [[150 160 170 180 190 200]]

 [[300 310 320 330 340 350]]

 [[100 110 120 130 140 150]]]


[187.5 197.5 207.5 217.5 227.5 237.5]
