In [1]:
#DIY 7 - 1

# Write a Python program that takes the speeds of any vehicle to store it in a NumPy array and calculates the average speed.
import numpy as np

num_v = int(input("Enter the number of vehicles :"))

arr = []
for i in range(0,num_v):
    speed = int(input(f"Enter the speed of the vehicle {i+1}: "))
    arr.append(speed)

speeds = np.array(arr)
aver = np.mean(arr)

print(speeds)
print(aver)
speeds.dtype

Enter the number of vehicles : 4
Enter the speed of the vehicle 1:  80
Enter the speed of the vehicle 2:  78
Enter the speed of the vehicle 3:  90
Enter the speed of the vehicle 4:  100


[ 80  78  90 100]
87.0


dtype('int32')

In [5]:
# Write a Python program to generate a 3-D array with integers of your choice,
# perform indexing, and print the first two rows and last two columns of the array

import numpy as np
import random

arr = np.random.randint(0,30,20).reshape(5,4)

# arr = np.arange(0,24).reshape(3,4,2)

# arr = np.random.random((2,2,2))

print(arr)
print("\n")
print("First two rows")
print(arr[0:2])


print("Last two columns")
print(arr[:,2:4])
arr.ndim

print("\n")
print("\n")


# ar = np.random.randint(0,30,20).reshape(2,5,2)
arr = np.arange(0,24).reshape(3,4,2)

# arr = np.random.random((2,2,2))
print("New Array")
print(ar)
print("\n")
print("First two rows")
print(ar[:,0:2,0:2])

print("\n")
print("Last two columns")
print(ar[:,0:,1])
arr.ndim

[[26 15  1 22]
 [ 3  7  6  3]
 [ 8 29  0  3]
 [27 23 10  3]
 [ 9 13 27 17]]


First two rows
[[26 15  1 22]
 [ 3  7  6  3]]
Last two columns
[[ 1 22]
 [ 6  3]
 [ 0  3]
 [10  3]
 [27 17]]




New Array
[[[18 14]
  [ 5 20]
  [10 23]
  [14 14]
  [ 9 20]]

 [[ 9  8]
  [ 6  2]
  [12 13]
  [24  9]
  [ 1  1]]]


First two rows
[[[18 14]
  [ 5 20]]

 [[ 9  8]
  [ 6  2]]]


Last two columns
[[14 20 23 14 20]
 [ 8  2 13  9  1]]


3

In [138]:
#DIY 7 - 2
# Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to
# make it 5*4 using suitable functions.

import numpy as np 

arr = np.arange(0,20).reshape(4,5)
print(arr)
print("\n")
b = np.transpose(arr)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [140]:
# '''Write a Python program to create two 2-dimensional arrays and apply
# hstack(), vstack(), concatenate(), and split() functions to
# them to get the output as shown below.'''

import numpy as np

# Create two 2-dimensional arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Horizontal stacking
hstack_result = np.hstack((array1, array2))
print("\nHorizontal Stack (hstack):")
print(hstack_result)

# Vertical stacking
vstack_result = np.vstack((array1, array2))
print("\nVertical Stack (vstack):")
print(vstack_result)

# Concatenation along the first axis (rows)
concat_result_axis0 = np.concatenate((array1, array2), axis=0)
print("\nConcatenate along the first axis (axis=0):")
print(concat_result_axis0)

# Concatenation along the second axis (columns)
concat_result_axis1 = np.concatenate((array1, array2), axis=1)
print("\nConcatenate along the second axis (axis=1):")
print(concat_result_axis1)

# Split array into multiple sub-arrays horizontally
split_result_h = np.hsplit(hstack_result, 2)
print("\nHorizontal Split (hsplit):")
for i, arr in enumerate(split_result_h):
    print(f"Split {i + 1}:")
    print(arr)

# Split array into multiple sub-arrays vertically
split_result_v = np.vsplit(vstack_result, 2)
print("\nVertical Split (vsplit):")
for i, arr in enumerate(split_result_v):
    print(f"Split {i + 1}:")
    print(arr)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Horizontal Stack (hstack):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertical Stack (vstack):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenate along the first axis (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenate along the second axis (axis=1):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Horizontal Split (hsplit):
Split 1:
[[1 2 3]
 [4 5 6]]
Split 2:
[[ 7  8  9]
 [10 11 12]]

Vertical Split (vsplit):
Split 1:
[[1 2 3]
 [4 5 6]]
Split 2:
[[ 7  8  9]
 [10 11 12]]


In [47]:
# ar = np.arange(0,24).reshape()
# array1 = np.array([[[1, 2, 3], [4, 5, 6]]])
# print(array1.shape)
# print(array1.ndim)
# arr = np.random.random((2,2,2))
ar = np.arange(0,20).reshape(1,5,4)
print("New Array")
print(ar)
print("\n")
print("First two rows")
print(ar[:,:2])

print("\n")
print("Last two columns")
print(ar[:,:,2:])


print("\n")


New Array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]


First two rows
[[[0 1 2 3]
  [4 5 6 7]]]


Last two columns
[[[ 2  3]
  [ 6  7]
  [10 11]
  [14 15]
  [18 19]]]




In [75]:
ar = np.arange(0,24).reshape(3,4,2)

# arr = np.random.random((2,2,2))
print("New Array")
print(ar)
print("\n")
print(ar[0:2,1:,0:1])
print("\n")
print(ar.shape)

New Array
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


[[[ 2]
  [ 4]
  [ 6]]

 [[10]
  [12]
  [14]]]


(3, 4, 2)
